### PR TITLE
gosu is not available; remove it from entry.sh

### PR DESCRIPTION
**Pull request by erlend-aasland**

### CODE REVIEW

**Comment by erlend-aasland** [comment]
🏓 @corona10

**Review by corona10 — APPROVED** [review]

**Comment by erlend-aasland** [comment]
@corona10, can you make a new release with this fix?

**Comment by corona10** [comment]
@erlend-aasland Do you have any thoughts about the version tag?

**Comment by erlend-aasland** [comment]
Hm, I don't know. Perhaps `272-{patch}` with increasing patch-numbers.

**Comment by erlend-aasland** [comment]
Or just overwrite the existing `272` tag. This is not official yet.

**Comment by corona10** [comment]
> Or just overwrite the existing 272 tag. This is not official yet.

I prefer to add a patch number; let's go.

**Pull request merged**
